// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mobile_svc.proto

/*
Package mobile is a generated protocol buffer package.

It is generated from these files:
	mobile_svc.proto

It has these top-level messages:
	GetWeatherRequest
	GetWeatherResponse
*/
package mobile

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import location "github.com/jamisonhyatt/grpc-multi-pkg-protos/pkg/external/location"
import weather "github.com/jamisonhyatt/grpc-multi-pkg-protos/pkg/external/weather"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetWeatherRequest struct {
	City *location.City `protobuf:"bytes,1,opt,name=city" json:"city,omitempty"`
}

func (m *GetWeatherRequest) Reset()                    { *m = GetWeatherRequest{} }
func (m *GetWeatherRequest) String() string            { return proto.CompactTextString(m) }
func (*GetWeatherRequest) ProtoMessage()               {}
func (*GetWeatherRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetWeatherRequest) GetCity() *location.City {
	if m != nil {
		return m.City
	}
	return nil
}

type GetWeatherResponse struct {
	Forecast *weather.Forecast `protobuf:"bytes,1,opt,name=forecast" json:"forecast,omitempty"`
}

func (m *GetWeatherResponse) Reset()                    { *m = GetWeatherResponse{} }
func (m *GetWeatherResponse) String() string            { return proto.CompactTextString(m) }
func (*GetWeatherResponse) ProtoMessage()               {}
func (*GetWeatherResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetWeatherResponse) GetForecast() *weather.Forecast {
	if m != nil {
		return m.Forecast
	}
	return nil
}

func init() {
	proto.RegisterType((*GetWeatherRequest)(nil), "mobile.GetWeatherRequest")
	proto.RegisterType((*GetWeatherResponse)(nil), "mobile.GetWeatherResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Mobile service

type MobileClient interface {
	GetWeather(ctx context.Context, in *GetWeatherRequest, opts ...grpc.CallOption) (*GetWeatherResponse, error)
}

type mobileClient struct {
	cc *grpc.ClientConn
}

func NewMobileClient(cc *grpc.ClientConn) MobileClient {
	return &mobileClient{cc}
}

func (c *mobileClient) GetWeather(ctx context.Context, in *GetWeatherRequest, opts ...grpc.CallOption) (*GetWeatherResponse, error) {
	out := new(GetWeatherResponse)
	err := grpc.Invoke(ctx, "/mobile.Mobile/GetWeather", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Mobile service

type MobileServer interface {
	GetWeather(context.Context, *GetWeatherRequest) (*GetWeatherResponse, error)
}

func RegisterMobileServer(s *grpc.Server, srv MobileServer) {
	s.RegisterService(&_Mobile_serviceDesc, srv)
}

func _Mobile_GetWeather_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWeatherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MobileServer).GetWeather(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mobile.Mobile/GetWeather",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MobileServer).GetWeather(ctx, req.(*GetWeatherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Mobile_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mobile.Mobile",
	HandlerType: (*MobileServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWeather",
			Handler:    _Mobile_GetWeather_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mobile_svc.proto",
}

func init() { proto.RegisterFile("mobile_svc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 241 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0x5d, 0x90, 0x22, 0x23, 0x88, 0x1b, 0x10, 0xb5, 0x27, 0xe9, 0xc9, 0x4b, 0x13, 0x58,
	0x0f, 0xde, 0x2d, 0xab, 0x27, 0x11, 0x7a, 0x11, 0xbc, 0x48, 0x1a, 0xc6, 0x36, 0x6e, 0xd3, 0x89,
	0xcd, 0x54, 0xe9, 0xbf, 0x17, 0x9a, 0x76, 0x15, 0xf4, 0x94, 0xf0, 0xbe, 0x99, 0x37, 0xf3, 0x06,
	0x4e, 0x1d, 0x55, 0xb6, 0xc5, 0xd7, 0xf0, 0x69, 0xa4, 0xef, 0x89, 0x49, 0x24, 0x51, 0x49, 0xcf,
	0x5b, 0x32, 0x9a, 0x2d, 0x75, 0x6a, 0xf9, 0xc4, 0x82, 0xf4, 0xec, 0x0b, 0x35, 0x37, 0xd8, 0xab,
	0xf9, 0x8d, 0x72, 0x76, 0x0b, 0xeb, 0x07, 0xe4, 0xe7, 0xa8, 0x95, 0xf8, 0x31, 0x60, 0x60, 0x91,
	0xc1, 0xa1, 0xb1, 0x3c, 0x5e, 0xac, 0xae, 0x56, 0xd7, 0xc7, 0x9b, 0x13, 0xb9, 0xb7, 0x2a, 0x2c,
	0x8f, 0xe5, 0xc4, 0xb2, 0x02, 0xc4, 0xef, 0xc6, 0xe0, 0xa9, 0x0b, 0x28, 0x72, 0x38, 0x7a, 0xa3,
	0x1e, 0x8d, 0x0e, 0x3c, 0x77, 0xaf, 0xe5, 0x32, 0xf0, 0x7e, 0x06, 0xe5, 0xbe, 0x64, 0xf3, 0x04,
	0xc9, 0xe3, 0xb4, 0xb7, 0xd8, 0x02, 0xfc, 0xd8, 0x89, 0x4b, 0x19, 0xe3, 0xc8, 0x3f, 0xbb, 0xa5,
	0xe9, 0x7f, 0x28, 0x4e, 0xcf, 0x0e, 0xee, 0xb6, 0x2f, 0x45, 0x6d, 0xb9, 0x19, 0x2a, 0x69, 0xc8,
	0xa9, 0x77, 0xed, 0x6c, 0xa0, 0xae, 0x19, 0x35, 0xb3, 0xaa, 0x7b, 0x6f, 0x72, 0x37, 0xb4, 0x6c,
	0x73, 0xbf, 0xab, 0xf3, 0x29, 0x7e, 0x50, 0x7e, 0x57, 0x2f, 0x17, 0x71, 0xba, 0x53, 0xd1, 0xbb,
	0x4a, 0x26, 0x7a, 0xf3, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x2a, 0x7a, 0x3e, 0xf4, 0x68, 0x01, 0x00,
	0x00,
}
